// Game catalog for Dani Cvjetnog
const GAMES = [
  {
    id: "sah",
    name: "Šah",
    players: 1,
    type: "Pojedinačna",
    schedule: "14:00 – 18:00",
    venue: "Desna Menza (2. linija)",
    spots: 16,
    taken: 9,
  },
  {
    id: "povlacenje",
    name: "Povlačenje užeta",
    players: 4,
    type: "Ekipa od 4",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 12,
    taken: 5,
  },
  {
    id: "treseta",
    name: "Trešeta",
    players: 2,
    type: "Par",
    schedule: "10:00 – 18:00",
    venue: "Desna Menza (2. linija)",
    spots: 16,
    taken: 11,
  },
  {
    id: "bela",
    name: "Bela",
    players: 2,
    type: "Par",
    schedule: "10:00 – 18:00",
    venue: "Desna Menza (2. linija)",
    spots: 16,
    taken: 7,
  },
  {
    id: "beerpong",
    name: "Beer pong",
    players: 2,
    type: "Par",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 24,
    taken: 18,
  },
  {
    id: "stolni-nogomet",
    name: "Stolni Nogomet",
    players: 2,
    type: "Par",
    schedule: "14:00 – 18:00",
    venue: "Društveni dom",
    spots: 16,
    taken: 0,
  },
  {
    id: "lov-na-blago",
    name: "Lov na blago",
    players: 1,
    type: "Pojedinačna",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 30,
    taken: 12,
  },
  {
    id: "alka",
    name: "Alka",
    players: 2,
    type: "Par",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 16,
    taken: 6,
  },
  {
    id: "pikado",
    name: "Pikado",
    players: 2,
    type: "Par",
    schedule: "TBD",
    venue: "Društveni dom",
    spots: 16,
    taken: 8,
  },
];

window.GAMES = GAMES;
