// Game catalog for Dani Cvjetnog
const GAMES = [
  {
    id: "sah",
    name: "Šah",
    players: 1,
    type: "Pojedinačna",
    blurb: "Tiha bitka na 64 polja. Donesi mirnu glavu i hladnu ruku.",
    schedule: "Pet · 18:00",
    venue: "Šator A",
    spots: 16,
    taken: 9,
  },
  {
    id: "povlacenje",
    name: "Povlačenje užeta",
    players: 4,
    type: "Ekipa od 4",
    blurb: "Četiri para tabana, jedno uže, jedna crta. Bez izgovora.",
    schedule: "Sub · 11:30",
    venue: "Veliko igralište",
    spots: 12,
    taken: 5,
  },
  {
    id: "treseta",
    name: "Trešeta",
    players: 2,
    type: "Par",
    blurb: "Dalmatinska klasika. Bez riječi, samo znakovi i karte.",
    schedule: "Pet · 20:00",
    venue: "Šator B",
    spots: 16,
    taken: 11,
  },
  {
    id: "bela",
    name: "Bela",
    players: 2,
    type: "Par",
    blurb: "Zovi, broji, šuti i pobjeđuj. Jedna od ovog vikenda.",
    schedule: "Sub · 15:00",
    venue: "Šator B",
    spots: 16,
    taken: 7,
  },
  {
    id: "beerpong",
    name: "Beer pong",
    players: 2,
    type: "Par",
    blurb: "Lopta, čaša, ruka koja ne drhti. Naizgled jednostavno.",
    schedule: "Sub · 21:00",
    venue: "Bar terasa",
    spots: 24,
    taken: 18,
  },
  {
    id: "pijani-konobar",
    name: "Pijani konobar",
    players: 1,
    type: "Pojedinačna",
    blurb: "Pladanj, čaše i ravnoteža koja popušta. Najsmiješnije za publiku.",
    schedule: "Sub · 19:00",
    venue: "Glavna pozornica",
    spots: 12,
    taken: 4,
  },
  {
    id: "lov-na-blago",
    name: "Lov na blago",
    players: 1,
    type: "Pojedinačna",
    blurb: "Tragovi po kvartu. Tko prvi sve riješi, prvi i slavi.",
    schedule: "Sub · 10:00",
    venue: "Cijelo naselje",
    spots: 30,
    taken: 12,
  },
  {
    id: "alka",
    name: "Alka",
    players: 2,
    type: "Par",
    blurb: "Naša lokalna izvedba — bez konja, ali s puno štosa.",
    schedule: "Ned · 12:00",
    venue: "Veliko igralište",
    spots: 16,
    taken: 6,
  },
  {
    id: "pikado",
    name: "Pikado",
    players: 2,
    type: "Par",
    blurb: "Tri strelice, jedna ruka, koncentracija na razini igle.",
    schedule: "Pet · 22:00",
    venue: "Bar terasa",
    spots: 16,
    taken: 8,
  },
];

window.GAMES = GAMES;
