// Game catalog for Dani Cvjetnog
const GAMES = [
  {
    id: "sah",
    name: "Šah",
    players: 1,
    type: "Pojedinačna",
    blurb: "Tiha bitka na 64 polja. Donesi mirnu glavu i hladnu ruku.",
    schedule: "14:00 – 18:00",
    venue: "Desna Menza (2. linija)",
    spots: 16,
    taken: 9,
  },
  {
    id: "povlacenje",
    name: "Povlačenje užeta",
    players: 4,
    type: "Ekipa od 4",
    blurb: "Četiri para tabana, jedno uže, jedna crta. Bez izgovora.",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 12,
    taken: 5,
  },
  {
    id: "treseta",
    name: "Trešeta",
    players: 2,
    type: "Par",
    blurb: "Dalmatinska klasika. Bez riječi, samo znakovi i karte.",
    schedule: "10:00 – 18:00",
    venue: "Desna Menza (2. linija)",
    spots: 16,
    taken: 11,
  },
  {
    id: "bela",
    name: "Bela",
    players: 2,
    type: "Par",
    blurb: "Zovi, broji, šuti i pobjeđuj. Jedna od ovog vikenda.",
    schedule: "10:00 – 18:00",
    venue: "Desna Menza (2. linija)",
    spots: 16,
    taken: 7,
  },
  {
    id: "beerpong",
    name: "Beer pong",
    players: 2,
    type: "Par",
    blurb: "Lopta, čaša, ruka koja ne drhti. Naizgled jednostavno.",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 24,
    taken: 18,
  },
  {
    id: "stolni-nogomet",
    name: "Stolni Nogomet",
    players: 2,
    type: "Par",
    blurb: "Dva stola, četiri ruke, jedna lopta. Brzo, glasno i bez milosti.",
    schedule: "14:00 – 18:00",
    venue: "Društveni dom",
    spots: 16,
    taken: 0,
  },
  {
    id: "lov-na-blago",
    name: "Lov na blago",
    players: 1,
    type: "Pojedinačna",
    blurb: "Tragovi po kvartu. Tko prvi sve riješi, prvi i slavi.",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 30,
    taken: 12,
  },
  {
    id: "alka",
    name: "Alka",
    players: 2,
    type: "Par",
    blurb: "Naša lokalna izvedba — bez konja, ali s puno štosa.",
    schedule: "TBD",
    venue: "Ispred 3. paviljona",
    spots: 16,
    taken: 6,
  },
  {
    id: "pikado",
    name: "Pikado",
    players: 2,
    type: "Par",
    blurb: "Tri strelice, jedna ruka, koncentracija na razini igle.",
    schedule: "TBD",
    venue: "Društveni dom",
    spots: 16,
    taken: 8,
  },
];

window.GAMES = GAMES;
